apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-app-config
  labels:
    app: auction-stack
data:
  MONGO_URI: "mongodb://mongo-service:27017/auctiondb"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: auction-app-secrets
  labels:
    app: auction-stack
stringData:
  JWT_SECRET: "change-me-in-prod"
